/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/book-appointment`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/welcome`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(doctor)'}/appoinments` | `/appoinments`; params?: Router.UnknownInputParams; } | { pathname: `${'/(doctor)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(patient)'}/appoinments` | `/appoinments`; params?: Router.UnknownInputParams; } | { pathname: `${'/(patient)'}/chatbot` | `/chatbot`; params?: Router.UnknownInputParams; } | { pathname: `${'/(patient)'}/health` | `/health`; params?: Router.UnknownInputParams; } | { pathname: `${'/(patient)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(patient)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(patient)'}/records` | `/records`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/book-appointment`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/signup`; params?: Router.UnknownOutputParams; } | { pathname: `/welcome`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(doctor)'}/appoinments` | `/appoinments`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(doctor)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(patient)'}/appoinments` | `/appoinments`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(patient)'}/chatbot` | `/chatbot`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(patient)'}/health` | `/health`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(patient)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(patient)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(patient)'}/records` | `/records`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/book-appointment${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/signup${`?${string}` | `#${string}` | ''}` | `/welcome${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(doctor)'}/appoinments${`?${string}` | `#${string}` | ''}` | `/appoinments${`?${string}` | `#${string}` | ''}` | `${'/(doctor)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(patient)'}/appoinments${`?${string}` | `#${string}` | ''}` | `/appoinments${`?${string}` | `#${string}` | ''}` | `${'/(patient)'}/chatbot${`?${string}` | `#${string}` | ''}` | `/chatbot${`?${string}` | `#${string}` | ''}` | `${'/(patient)'}/health${`?${string}` | `#${string}` | ''}` | `/health${`?${string}` | `#${string}` | ''}` | `${'/(patient)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(patient)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(patient)'}/records${`?${string}` | `#${string}` | ''}` | `/records${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/book-appointment`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/welcome`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(doctor)'}/appoinments` | `/appoinments`; params?: Router.UnknownInputParams; } | { pathname: `${'/(doctor)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(patient)'}/appoinments` | `/appoinments`; params?: Router.UnknownInputParams; } | { pathname: `${'/(patient)'}/chatbot` | `/chatbot`; params?: Router.UnknownInputParams; } | { pathname: `${'/(patient)'}/health` | `/health`; params?: Router.UnknownInputParams; } | { pathname: `${'/(patient)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(patient)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(patient)'}/records` | `/records`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
